### ISSUE TITLE
Error in breaking down resource with regex

### ISSUE THREAD

**Issue by ganeshsankaran** [ucsb-ersp-2019/UCSB-ERSP-SEC-2019-2020#5]
If the resource is <code>"arn:aws:iam::*:user/${aws:username}"</code>, then the function that splits the resource by <code>:</code> results in the SMT output containing <code>(= "user/${aws" resourceResource)</code>.

**Comment by Albli001348** [comment]
Maybe we should have some check to see if there are more than 5 elements in the resulting list and merge the last elements together to assert against resourceResource

**Comment by ganeshsankaran** [comment]
We were able to fix this in the form above, but we'll have to find out if any other places could have that weird syntax

**Comment by ganeshsankaran** [comment]
We are going to be treating these as literal text
